//! b4fill2 (loop5 iter15, 2026-08-21): decoder+encoder coverage for the rt98
//! era classes that fell into `/* ? */` passthrough under tables/sm103a.json
//! (the M4.8 sm103 A/B blocker after b4fill). Rows derived from rt98 gold
//! words (silicon-proven sm120 lineage, cross-decoded by nvdisasm under an
//! sm_103 ELF shell in b4fill): per-token brute-force window fit + sibling
//! (tb_i82p3) geometry verification; and_base/variable_mask recomputed over
//! the native samples; era-epoch hi32 statics kept native (never sm120-harvest
//! constants). Invisible desc-policy bits carry fresh !rsd (regenerated by the
//! disassembler), per doctrine "rsd where bits are invisible to text".
//! Provenance: /root/blindlab/results/b4/b4fill2 (derivation logs + gate).
use cubit::decoder::DecodeIndex;
use cubit::encoder::encode_instruction;
use cubit::parser::parse_sass;
use cubit::table::IsaTable;

fn t103a() -> IsaTable {
    IsaTable::load(std::path::Path::new("tables/sm103a.json")).unwrap()
}
const SCHED: u128 = 0xFFFF_FFFFu128 << 96;

static GOLD: &[(u128, &str)] = &[
    // (the four era "LDG.E.LTC128B.128"-glif words formerly pinned here are
    // resolved under BUG-094: the LDS.128 .X16 one returns below with vendor
    // text; the 3 raw-address LDG/STG era forms are fail-closed pins in
    // render_only pending F2Q-099 coverage)
    // IADD3.X: cout pred at [83:81] (table regression fix), II form
    (0x000fe2000071e4ff0000005935355210u128, "@P5 IADD3.X R53, P0, PT, R53, R89, RZ, P0, !PT"),
    (0x080fe80007f3e4fffffffc2f74748810u128, "@!P0 IADD3.X R116, P1, PT, R116, -0x3d1, RZ, !PT, !PT"),
    // LOP3.LUT.PAND predicated 7-token
    (0x000fe6000309c0ff0000080048ff7812u128, "LOP3.LUT.PAND P4, RZ, R72, 0x800, RZ, 0xc0, P6"),
    // ATOMG/REDG .EL.STRONG.GPU descriptor forms
    (0x000f6400082ee10600000051ffda39a8u128, "@P3 ATOMG.E.ADD.EL.STRONG.GPU PT, R218, desc[UR6][RZ.64], R81"),
    (0x0009e4000820e11400000051d100498eu128, "@P4 REDG.E.ADD.EL.STRONG.GPU PT, desc[UR20][R209.64], R81"),
    (0x0009e4000aa0e1140a2400404200298eu128, "@P2 REDG.E.AND.EL.STRONG.GPU PT, desc[UR20][R66.64+0xa2400], R64"),
    (0x0009e4000b20e1140a2400171900798eu128, "REDG.E.OR.EL.STRONG.GPU PT, desc[UR20][R25.64+0xa2400], R23"),
    // UIMAD 5-token uniform II form (URZ tok then UR63 overwrite at [71:64])
    (0x000ff2000f8e003f00003000351278a4u128, "UIMAD.U32 UR18, UR53, 0x3000, UR63"),
    (0x000fe2000f8e003f00000100242278a4u128, "UIMAD.U32 UR34, UR36, 0x100, UR63"),
    // IMAD.X 5-token with pred
    (0x000fe200010e045d0000006408423224u128, "@P3 IMAD.X R66, R8, R100, R93, P2"),
    // LDS.128 .X16 (BUG-094: NV-proven true identity of this era slot; decodes
    // vendor-exact on both tables via the LDS_R_ARI::128 addr_scale field)
    (0x000ee4000000cc0000000000091c8984u128, "@!P0 LDS.128 R28, [R9.X16]"),
    (0x000e64000000cc000000000003587984u128, "LDS.128 R88, [R3.X16]"),
    // STS.128 with .X16 address scale (note: the R204 era sibling moved to
    // b4fill2_render_only under BUG-088 -- the encoder fails closed on it)
    (0x001be4000000cc00000000c805007388u128, "STS.128 [R5.X16], R200"),
];

#[test]
fn b4fill2_decode_render_reencode_exact() {
    let t = t103a();
    let idx = DecodeIndex::build(&t);
    let mut fails = Vec::new();
    for &(word, golden) in GOLD {
        let d = match idx.decode(word, 0, &t) {
            Ok(d) => d,
            Err(e) => { fails.push(format!("word {word:032x}: decode fail: {e}")); continue; }
        };
        let text = cubit::printer::to_sass(&d);
        if text != golden {
            fails.push(format!("word {word:032x}: render {text:?} != golden {golden:?}"));
            continue;
        }
        let insn = parse_sass(&format!("{text} ;"), 0).unwrap();
        let w2 = encode_instruction(&insn, &t).unwrap();
        // compare only field-owned + static-and_base region of the matched row:
        // invisible desc-policy / epoch bits are !rsd-carried by the file-level
        // disassembler (covered by the full-file byte-exact gate), not by text.
        let (key, mg) = (d.key.clone(), d.mod_group.clone());
        let e = t.get(&key, &mg).unwrap();
        let mut fm: u128 = 0;
        for f in &e.fields {
            if f.extraction == cubit::table::Extraction::None { continue; } // phantom: rsd-carried
            fm |= ((1u128 << f.bits) - 1) << f.shift;
        }
        let mut keep = (!e.variable_mask | fm) & !SCHED;
        // statics in the era-epoch hi32 are not text-carried either; file-level
        // !rsd covers them. keep them only when the row's and_base claims them.
        let _ = &mut keep;
        if (w2 & keep) != (word & keep) {
            fails.push(format!("re-encode diff {w2:032x} vs {word:032x} (keep {keep:032x})"));
        }
    }
    assert!(fails.is_empty(), "{} failures:\n{}", fails.len(), fails[..fails.len().min(5)].join("\n"));
}

#[test]
fn b4fill2_render_only() {
    // branch/immediate residuum: bare-text re-encode would need the !rsd
    // overlay (file-level machinery) — pin decode+render; roundtrip is the
    // full-file byte-exact gate (results/b4/b4fill2).
    let t = t103a();
    let idx = DecodeIndex::build(&t);
    for &(word, golden) in &[
        // BUG-059: consumer IMNMX era words stay DECODE-ONLY on sm_103a
        // (silicon-ILLEGAL per m48 P1-P3); encoder rejects them fail-closed
        // (tests/bug059_imnmx_sm103.rs pins the reject + sm120 control).
        (0x020fec00038002000003ffffdada7817u128, "IMNMX.S64 P0, P0, |R218|, R218, 0x3ffff, PT, P0"),
        (0x000fe200080400000000002aff407947u128, "BRA.DIV P0, URZ, 0x2910"),
        (0x000fe2000c04000000000003ff047947u128, "BRA.CONV !P0, URZ, 0x20"),
        (0x000ff2000b83ffffffffffdd1e7c7958u128, "BRXU.U UR30, -0x1"),
        (0x000fe2000b80000000000005ff447958u128, "BRXU.U URZ, 0x11"),
        // BUG-088: the R204-era STS.128 word violates the sm_103a .128 data
        // alignment law (quad 51 odd, >=11 -- direct silicon probe of the
        // verbatim era shape traps II; runtime-dead path in the certified
        // kernel). Stay DECODE-ONLY; encoder reject is pinned in
        // tests/bug088_wide_mem_reg_align.rs t4.
        (0x000be4000000cc00000010cc05007388u128, "STS.128 [R5.X16+0x10], R204"),
    ] {
        let d = idx.decode(word, 0, &t).unwrap();
        assert_eq!(cubit::printer::to_sass(&d), golden);
    }
    // BUG-094: the four era words below were pinned (b4fill2, iter15) to the
    // LDG.E.LTC128B.128 desc-UR glif emitted by the harvest-junk catch-all
    // modgroup LDG_R_dARI::128,E,LTC128B. Word-level nvdisasm-13.3 probes
    // (work/f2-094/era249_nv2.json) prove each is a DIFFERENT memory op:
    //   0x000e2400181e0b000000000806087981 -> LDG.E.64 R8, [R6.U32+UR8]
    //   0x000e64000000cc000000000003587984 -> LDS.128 R88, [R3.X16]
    //   0x0007e40008100b0c0000003444007986 -> STG.E.64 [R68.U32+UR12], R52
    //   0x000e2400181e0b0000080008060a7981 -> LDG.E.64 R10, [R6.U32+UR8+0x800]
    // The junk modgroup (zero vendor-true traffic over the 885k-word census;
    // 100% offender classes) was deleted; canon does not yet cover these
    // raw-address uniform-indexed era forms (F2Q candidate 099), so decode is
    // FAIL-CLOSED here (file-level output carries /* ? 0x... */ markers).
    // Era-text encode stays byte-exact via the encode_only retention row
    // LDG.E.LTC128B.128_R_dARI (pinned in tests/bug094_lds_ldl_stl_cas.rs).
    // Post-BUG-094 follow-up: canon got the addr_scale [79:78] field on
    // LDS_R_ARI::64/128 (i108-era nvdisasm-verified anchors), so the
    // LDS.128 .X16 era word now decodes VENDOR-EXACT: it lives in GOLD above.
    // The 3 remaining words are raw-address uniform-indexed LDG/STG era forms
    // canon does not cover yet (F2Q-099; sm120.json decodes all three
    // vendor-exact today via its LDG/STG keys).
    // BUG-099 (F2-iter36): canon coverage for the raw-address uniform-indexed
    // era forms LANDED (donor keys imported verbatim from sm120 + 095 repair
    // of LDG_R_ARURI::E). Decode is now VENDOR-EXACT on both tables (era dec
    // re-pin NOTE_099: all 193 changed slots == nvdisasm text); the
    // fail-closed pin is retired into an exact-render pin.
    for &(word, golden) in &[
        (0x000e2400181e0b000000000806087981u128, "LDG.E.64 R8, [R6.U32+UR8]"),
        (0x0007e40008100b0c0000003444007986u128, "STG.E.64 [R68.U32+UR12], R52"),
        (0x000e2400181e0b0000080008060a7981u128, "LDG.E.64 R10, [R6.U32+UR8+0x800]"),
    ] {
        let d = idx.decode(word, 0, &t).unwrap();
        assert_eq!(cubit::printer::to_sass(&d), golden);
    }
}
