//! b9p13 (phase-3 #11) pins: add.sat.s32 (PLOP3.LUT R.SIGN row) + mufu lane
//! (abs.f32 / tanh / sin / cos / ex2 / lg2 / div.approx vendor -O0 macros) +
//! guess-fixes (sin/cos scale, ex2/lg2 range guards) + call-lane fail-closed
//! (rcp.rn/sqrt.rn/div.rn, vendor lowers via CALL.REL.NOINC slowpath).
//! Anchors: results/b9/b9p13_parity (108 payload words IDENT, O0+O3),
//! probes regenerated byte-identical with ptxas 13.3 (md5 manifest).
//! Doctrine: fail-closed on unanchored shapes.
use cubit::ptx_lower::lower_kernel;
use cubit::ptx_parse::parse_ptx;
use cubit::table::IsaTable;

/// hex helper (no external crates in dev-deps).
fn hx(s: &str) -> Vec<u8> {
    (0..s.len()).step_by(2).map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap()).collect()
}

fn table() -> IsaTable {
    IsaTable::load(std::path::Path::new("tables/sm103a.json")).unwrap()
}
fn assemble_body(text: &str) -> (Vec<u8>, usize) {
    let body: String = text.lines()
        .filter(|l| !l.trim_start().starts_with('.'))
        .collect::<Vec<_>>().join("\n");
    cubit::assemble(&body, 0, &table()).unwrap()
}
const PROLOG: &str = ".version 9.3\n.target sm_103a\n.address_size 64\n\n";
fn kern(body: &str) -> String {
    format!(r#"{} .visible .entry k(
    .param .u64 .ptr .align 1 k_param_0
)
{{
    .reg .pred %p<8>;
    .reg .b32  %r<40>;
    .reg .b64  %rd<10>;
    ld.param.b64 %rd1, [k_param_0];
    cvta.to.global.u64 %rd2, %rd1;
{}
    ret;
}}"#, PROLOG, body)
}
fn lower(body: &str) -> String {
    let k = parse_ptx(&kern(body)).unwrap();
    lower_kernel(&k[0]).unwrap().to_sass_text()
}
fn lower_err(body: &str) -> String {
    let k = parse_ptx(&kern(body)).unwrap();
    match lower_kernel(&k[0]) { Ok(_) => String::new(), Err(e) => format!("{:#}", e) }
}
fn lines_of(text: &str) -> Vec<String> {
    text.lines().map(|l| l.trim()).filter(|l| l.ends_with(';')).map(|l| l.to_string()).collect()
}
fn shape(l: &[String]) -> Vec<String> {
    let re = regex::Regex::new(r"\b(?:R|UR|P)(\d+)(\.64)?\b").unwrap();
    let mut out = Vec::new();
    let mut map: std::collections::HashMap<String, usize> = std::collections::HashMap::new();
    for ll in l {
        let s = re.replace_all(ll, |c: &regex::Captures| {
            let t = format!("{}{}", &c[1], c.get(2).map(|m| m.as_str()).unwrap_or(""));
            if t == "255" || t == "255.64" { return "255".to_string(); }
            let k = t.clone();
            let n = map.len();
            let v = map.entry(k).or_insert(n);
            format!("@{v}{}", c.get(2).map(|m| m.as_str()).unwrap_or(""))
        });
        out.push(s.to_string());
    }
    out
}
fn shape_from(text: &str, marker_substr: &str) -> Vec<String> {
    let mut l = lines_of(text);
    let i = l.iter().position(|x| x.contains(marker_substr)).expect(marker_substr);
    l.drain(..i);
    shape(&l)
}

/// 1. add.sat.s32 -> 5-op vendor -O0 macro (anchor corpus p27 0x290-0x2d0):
/// IADD3 + 2x PLOP3.LUT R.SIGN + 2x SEL. Structural pin (RA-agnostic).
#[test]
fn b9p13_addsat_shape() {
    let t = lower("    ld.global.s32 %r1, [%rd2];\n    ld.global.s32 %r2, [%rd2+0x4];\n    add.sat.s32 %r3, %r1, %r2;");
    let l = shape_from(&t, "IADD3");
    assert_eq!(l[1], "PLOP3.LUT @3, PT, @1, @2, @0, 0x2, 0x0 ;", "{l:?}");
    assert_eq!(l[2], "PLOP3.LUT @4, PT, @1, @2, @0, 0x40, 0x0 ;", "{l:?}");
    assert_eq!(l[3], "SEL @0, @0, 0x7fffffff, !@3 ;", "{l:?}");
    assert_eq!(l[4], "SEL @0, @0, 0x80000000, !@4 ;", "{l:?}");
}

/// 2. add.sat.s32 ENCODE byte-parity vs harvested vendor anchors (payload
/// bytes[0:12]; anchors corpus p27 O0 0x290-0x2d0, md5_manifest).
#[test]
fn b9p13_addsat_encode_parity() {
    let (b, n) = assemble_body(
        "IADD3 R7, PT, PT, R5, R6, RZ ;
         PLOP3.LUT P0, PT, R5.SIGN, R6.SIGN, R7.SIGN, 0x2, 0x0 ;
         PLOP3.LUT P1, PT, R5.SIGN, R6.SIGN, R7.SIGN, 0x40, 0x0 ;
         SEL R6, R7, 0x7fffffff, !P0 ;
         SEL R6, R6, 0x80000000, !P1 ;");
    assert_eq!(n, 5);
    let want: [&str; 5] = [
        "1072070506000000ffe0ff07",
        "1f7200050600000007027000",
        "1f7200050600000007407200",
        "07780607ffffff7f00000004",
        "077806060000008000008004",
    ];
    for (i, w) in want.iter().enumerate() {
        assert_eq!(&b[i*16..i*16+12], &hx(w)[..],
                   "word {i} payload mismatch");
    }
}

/// 3. PLOP3.SIGN row: guard field live (@P0 variant), lutB field live,
///    parser drops .SIGN (row carries semantics). Anchors: nvdisasm
///    bit-patch probes work/b9p13/t/probe2_*.
#[test]
fn b9p13_plop3sign_fields() {
    let (b, n) = assemble_body(
        "@P0 PLOP3.LUT P1, PT, R4.SIGN, R5.SIGN, R10.SIGN, 0x2, 0x0 ;");
    assert_eq!(n, 1);
    // guard @12(4)=0 (P0), pd@81=1, a@24=4, b@32=5, c@64=10, lutA@72=2
    let w = u128::from_le_bytes(b[..16].try_into().unwrap());
    assert_eq!((w >> 12) & 0xf, 0, "guard");
    assert_eq!((w >> 81) & 7, 1, "pd");
    assert_eq!((w >> 24) & 0xff, 4, "a");
    assert_eq!((w >> 32) & 0xff, 5, "b");
    assert_eq!((w >> 64) & 0xff, 10, "c");
    assert_eq!((w >> 72) & 0xff, 2, "lutA");
    let (b2, _) = assemble_body("PLOP3.LUT P2, PT, R3.SIGN, R12.SIGN, R4.SIGN, 0x2, 0x8 ;");
    let w2 = u128::from_le_bytes(b2[..16].try_into().unwrap());
    assert_eq!((w2 >> 16) & 0xff, 8, "lutB");
    assert_eq!((w2 >> 81) & 7, 2, "pd");
}

/// 4. sin.approx.f32 -> FMUL.RZ + MUFU.SIN (scale 1/2pi NOT dropped; p18 O0
/// 0x4d0-0x4e0). cos -> MUFU.COS sibling.
#[test]
fn b9p13_sincos_shape_and_parity() {
    let t = lower("    ld.global.b32 %r1, [%rd2];\n    sin.approx.f32 %r2, %r1;");
    let l = shape_from(&t, "FMUL.RZ");
    assert_eq!(l[0], "FMUL.RZ @0, @1, 0x3e22f983F ;", "{l:?}");
    assert_eq!(l[1], "MUFU.SIN @2, @0 ;", "{l:?}");
    let t2 = lower("    ld.global.b32 %r1, [%rd2];\n    cos.approx.f32 %r2, %r1;");
    let l2 = shape_from(&t2, "FMUL.RZ");
    assert_eq!(l2[1], "MUFU.COS @2, @0 ;", "{l2:?}");
    let (b, n) = assemble_body("FMUL.RZ R9, R5, 0.15915493667125701904 ;\nMUFU.SIN R9, R9 ;");
    assert_eq!(n, 2);
    assert_eq!(&b[0..12], &hx("2078090583f9223e00c04000")[..]);
    assert_eq!(&b[16..28], &hx("087309000900000000040000")[..]);
}

/// 5. ex2.approx.f32 -> 6-op range macro (p18 O0 0x2a0-0x320, FI-folded);
///    lg2.approx.f32 -> 7-op denormal macro (0x3e0-0x4a0).
#[test]
fn b9p13_ex2_lg2_shapes() {
    let t = lower("    ld.global.b32 %r1, [%rd2];\n    ex2.approx.f32 %r2, %r1;");
    let l = shape_from(&t, "FSETP.LT.AND");
    assert_eq!(l[0], "FSETP.LT.AND @0, PT, @1, 0xc2fc0000F, PT ;", "{l:?}");
    assert_eq!(l[1], "FMUL @2, @1, 0x3f000000F ;");
    assert_eq!(l[2], "FSEL @2, @2, @1, @0 ;");
    assert_eq!(l[3], "MUFU.EX2 @2, @2 ;");
    assert_eq!(l[4], "FMUL @3, @2, @2 ;");
    assert_eq!(l[5], "FSEL @4, @3, @2, @0 ;");
    let t2 = lower("    ld.global.b32 %r1, [%rd2];\n    lg2.approx.f32 %r2, %r1;");
    let l2 = shape_from(&t2, "FADD");
    assert_eq!(l2[0], "FADD @0, -RZ, |@1| ;", "{l2:?}");
    assert_eq!(l2[1], "FSETP.LT.AND @2, PT, @0, 0x00800000F, PT ;");
    assert_eq!(l2[2], "FMUL @3, @1, 0x4b800000F ;");
    assert_eq!(l2[3], "FSEL @3, @3, @1, @2 ;");
    assert_eq!(l2[4], "MUFU.LG2 @3, @3 ;");
    assert_eq!(l2[5], "FADD @4, @3, 0xc1c00000F ;");   // -24.0
    assert_eq!(l2[6], "FSEL @5, @4, @3, @2 ;");
}

/// 6.

/// 6. div.approx.f32 -> 8-op macro (mufu1 O0 0x1c0-0x280, FI-folded: FSETP/FMUL
///    imm slots, O3-anchor). Tanh/abs single-op forms.
#[test]
fn b9p13_divapprox_tanh_abs_shapes() {
    let t = lower("    ld.global.b32 %r1, [%rd2];\n    ld.global.b32 %r2, [%rd2+0x4];\n    div.approx.f32 %r3, %r1, %r2;");
    let l = shape_from(&t, "FADD");
    let ls: Vec<String> = l.into_iter().filter(|x| !x.contains("LDC")).collect();
    let exp = [
        "FADD @0, -RZ, |@1| ;",
        "FSETP.LT.AND @2, PT, @0, 0x00800000F, PT ;",
        "FMUL @3, @1, 0x4b800000F ;",
        "FSEL @3, @3, @1, @2 ;",
        "MUFU.RCP @3, @3 ;",
        "FMUL @4, @5, 0x4b800000F ;",
        "FSEL @4, @4, @5, @2 ;",
        "FMUL @6, @4, @3 ;",
    ];
    for e in exp { assert!(ls.iter().any(|x| x == e), "missing {e} in {ls:?}"); }
    let t2 = lower("    ld.global.b32 %r1, [%rd2];\n    tanh.approx.f32 %r2, %r1;\n    abs.f32 %r3, %r1;");
    let l2 = shape_from(&t2, "MUFU.TANH");
    assert_eq!(l2[0], "MUFU.TANH @0, @1 ;");
    assert_eq!(l2[1], "FADD @2, -RZ, |@1| ;");
    // abs.f32 + tanh encode parity (p18 O0 anchors)
    let (b, _) = assemble_body("FADD R7, -RZ, |R5| ;\nMUFU.TANH R9, R5 ;");
    assert_eq!(&b[0..12], &hx("217207ff0500004000010000")[..]);
    assert_eq!(&b[16..28], &hx("087309000500000000240000")[..]);
}

/// 7. fail-closed: imm operand / guarded / unanchored suffixes; call-lane
///    rcp.rn/sqrt.rn/div.rn surface as unsupported (vendor CALL slowpath).
#[test]
fn b9p13_fail_closed() {
    let e = lower_err("    ld.global.b32 %r1, [%rd2];\n    add.sat.s32 %r3, %r1, 0x5;");
    assert!(e.contains("add.sat.s32"), "{e}");
    let e = lower_err("    setp.lt.s32 %p1, %r1, 0;\n    @%p1 sin.approx.f32 %r2, %r1;");
    assert!(e.contains("sin.approx"), "{e}");
    let e = lower_err("    ld.global.b32 %r1, [%rd2];\n    sin.approx.ftz.f32 %r2, %r1;");
    assert!(e.contains("sin.approx.ftz"), "{e}");
    for op in ["rcp.rn.f32", "sqrt.rn.f32", "div.rn.f32"] {
        let e = lower_err(&format!("    ld.global.b32 %r1, [%rd2];\n    {op} %r2, %r1;"));
        assert!(e.contains(op), "{op}: {e}");
    }
    let e = lower_err("    ld.global.b32 %r1, [%rd2];\n    ex2.approx.ftz.f32 %r2, %r1;");
    assert!(e.contains("ex2.approx.ftz"), "{e}");
}

/// 8. label-stability: branch over a macro lands on the right target
///    (expansion-size contract = the emitted counts).
#[test]
fn b9p13_label_stability() {
    let t = lower("    ld.global.b32 %r1, [%rd2];\n    setp.lt.s32 %p1, %r1, 0;\n    @%p1 bra BB1;\n    add.sat.s32 %r3, %r1, %r2;\nBB1:\n    mov.b32 %r4, 0;");
    let bra = lines_of(&t).into_iter().position(|l| l.starts_with("@P") || l.starts_with("@!P")).unwrap();
    let mut bb1_line = None;
    for (i, l) in t.lines().enumerate() {
        if l.trim() == "BB1:" { bb1_line = Some(i); }
    }
    assert!(bb1_line.is_some(), "label survived: {t}");
    let bra_text = &lines_of(&t)[bra];
    assert!(bra_text.contains("BB1"), "{bra_text}");
}
